FROM node:22-slim

# copied from puppeteer dockerfile
# https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile
ENV \
    # Configure default locale (important for chrome-headless-shell).
    LANG=en_US.UTF-8 \
    # UID of the non-root user 'pptruser'
    PPTRUSER_UID=10042

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chrome that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y --no-install-recommends fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros \
    fonts-kacst fonts-freefont-ttf dbus dbus-x11

# Install extra puppeteer dependencies
# https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    wget \
    xdg-utils

# Install other dependencies (mostly for thecoin/signers)
RUN apt-get install -y --no-install-recommends \
    xz-utils \
    python3 \
    make \
    g++ \
    libusb-1.0-0-dev \
    pkg-config \
    libudev-dev \
    xvfb \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Add pptruser.
RUN groupadd -r pptruser && useradd -u $PPTRUSER_UID -rm -g pptruser -G audio,video pptruser

USER $PPTRUSER_UID

WORKDIR /home/pptruser

ENV DBUS_SESSION_BUS_ADDRESS=autolaunch:

# Install system dependencies as root.
USER root

# Setup directory structure
# - /thecoin for the app itself
# - /environments for build-time config
# - /data for runtime persistent data
# - /secrets for sensitive credentials
RUN mkdir -p \
  /home/pptruser/Downloads \
  /thecoin \
  /thecoin/environments \
  /data/logs \
  /data/dbs \
  /data/profiles \
  /secrets

RUN chown -R pptruser:pptruser /home/pptruser \
  && chown -R pptruser:pptruser /thecoin \
  && chown -R pptruser:pptruser /data \
  && chown -R pptruser:pptruser /secrets \
  && chmod 700 /secrets

# Setup Yarn 4.x
RUN corepack enable

# Run everything after as non-privileged user.
USER pptruser

COPY --chown=pptruser:pptruser package.json yarn.lock .yarnrc.yml /thecoin/
COPY --chown=pptruser:pptruser libs /thecoin/libs
COPY --chown=pptruser:pptruser apis /thecoin/apis
COPY --chown=pptruser:pptruser apps/tx-processor /thecoin/apps/tx-processor
COPY --chown=pptruser:pptruser environments/*.env /thecoin/environments

WORKDIR /thecoin/apps/tx-processor

# Set default environment & disable typescript processing
ENV NODE_ENV=production \
    PUPPETEER_SKIP_DOWNLOAD=true \
    TS_NODE_PROJECT=none \
    THECOIN_CONSOLE_ONLY=true \
    THECOIN_DATA=/data \
    TC_LOG_FOLDER=/data/logs \
    STORAGE_PATH=/data/dbs/ \
    THECOIN_SECRETS=/secrets

# Copy workspace files
# COPY temp/package.json ./
# COPY temp/.yarnrc.yml ./
# COPY temp/yarn.lock ./

# Install dependencies and cleanup sensitive files
RUN yarn workspaces focus --production && \
    rm -f .yarnrc.yml


# RUN mkdir -p /data/dbs && \
#     mkdir -p /data/logs && \
#     mkdir -p /data/profiles
    # mkdir -p /secrets && \
    # Ensure secrets directory has restricted permissions
    # chmod 700 /secrets

# Copy environment configs
# COPY ./environments/*.env /environments/

# Create volume mount points
VOLUME /data
VOLUME /secrets

# Hard-code the path to run-env to avoid issues with
# Yarn not thinking it's been installed
CMD ["yarn", "start"]
