/** Declaration file generated by dts-gen */

declare module 'identity-wallet' {
    class identity_wallet {
        constructor(getConsent: any, ...args: any[]);
    
        addAuthMethod(authSecret: any): any;
    
        authenticate(...args: any[]): any;
    
        decrypt(encObj: any, space: any, toBuffer: any): any;
    
        encrypt(message: any, space: any, ...args: any[]): any;
    
        get3idProvider(): any;
    
        getConsent(...args: any[]): any;
    
        getLink(): any;
    
        hasConsent(...args: any[]): any;
    
        hashDBKey(key: any, space: any): any;
    
        isAuthenticated(...args: any[]): any;
    
        linkAddress(address: any, provider: any): any;
    
        linkManagementKey(): any;
    
        signClaim(payload: any, ...args: any[]): any;
    
    }

    export = identity_wallet;
}