:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore Server\TapCapSupplier.Server
dotnet build Server\TapCapSupplier.Server
echo Now, run the following to start the project: dotnet run -p Server\TapCapSupplier.Server\TapCapSupplier.Server.csproj --launch-profile web.
echo.
