approvedGitRepositories:
  - "https://github.com/electron/node-gyp*"
  - "https://github.com/FrozenKiwi/exif-library*"
  - "https://github.com/FrozenKiwi/forge-externals-plugin-monorepo*"
  - "https://github.com/FrozenKiwi/redux-injectors*"
  - "https://github.com/thecointech/firestore-jest-mock*"

checksumBehavior: ignore

enableScripts: true

nodeLinker: node-modules

# prevent installing packages installed less than N seconds ago.
# 0 effectively disables this.
npmMinimalAgeGate: 0
