/**
 * THE Coin Broker Sample
 * TheCoin simple broker services.  This sample API is an example of how to setup the simplest low-volume exchange, when combined with the included server code, without external dependencies
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertifiedTransferRequest model module.
 * @module model/CertifiedTransferRequest
 * @version 0.1.0
 */
class CertifiedTransferRequest {
    /**
     * Constructs a new <code>CertifiedTransferRequest</code>.
     * @alias module:model/CertifiedTransferRequest
     * @param from {String} 
     * @param to {String} 
     * @param value {Number} 
     * @param fee {Number} 
     * @param timestamp {Number} 
     * @param signature {String} 
     */
    constructor(from, to, value, fee, timestamp, signature) { 
        
        CertifiedTransferRequest.initialize(this, from, to, value, fee, timestamp, signature);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, from, to, value, fee, timestamp, signature) { 
        obj['from'] = from;
        obj['to'] = to;
        obj['value'] = value;
        obj['fee'] = fee;
        obj['timestamp'] = timestamp;
        obj['signature'] = signature;
    }

    /**
     * Constructs a <code>CertifiedTransferRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertifiedTransferRequest} obj Optional instance to populate.
     * @return {module:model/CertifiedTransferRequest} The populated <code>CertifiedTransferRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertifiedTransferRequest();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} from
 */
CertifiedTransferRequest.prototype['from'] = undefined;

/**
 * @member {String} to
 */
CertifiedTransferRequest.prototype['to'] = undefined;

/**
 * @member {Number} value
 */
CertifiedTransferRequest.prototype['value'] = undefined;

/**
 * @member {Number} fee
 */
CertifiedTransferRequest.prototype['fee'] = undefined;

/**
 * @member {Number} timestamp
 */
CertifiedTransferRequest.prototype['timestamp'] = undefined;

/**
 * @member {String} signature
 */
CertifiedTransferRequest.prototype['signature'] = undefined;






export default CertifiedTransferRequest;

