/**
 * THE Coin Broker Sample
 * TheCoin simple broker services.  This sample API is an example of how to setup the simplest low-volume exchange, when combined with the included server code, without external dependencies
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PurchaseComplete from './PurchaseComplete';
import SignedPurchaseConfirm from './SignedPurchaseConfirm';
import SignedPurchaseRequest from './SignedPurchaseRequest';

/**
 * The PurchaseState model module.
 * @module model/PurchaseState
 * @version 0.1.2
 */
class PurchaseState {
    /**
     * Constructs a new <code>PurchaseState</code>.
     * @alias module:model/PurchaseState
     */
    constructor() { 
        
        PurchaseState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PurchaseState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseState} obj Optional instance to populate.
     * @return {module:model/PurchaseState} The populated <code>PurchaseState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseState();

            if (data.hasOwnProperty('request')) {
                obj['request'] = SignedPurchaseRequest.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('confirm')) {
                obj['confirm'] = SignedPurchaseConfirm.constructFromObject(data['confirm']);
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = PurchaseComplete.constructFromObject(data['complete']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SignedPurchaseRequest} request
 */
PurchaseState.prototype['request'] = undefined;

/**
 * @member {module:model/SignedPurchaseConfirm} confirm
 */
PurchaseState.prototype['confirm'] = undefined;

/**
 * @member {module:model/PurchaseComplete} complete
 */
PurchaseState.prototype['complete'] = undefined;






export default PurchaseState;

