/**
 * THE Coin Broker Sample
 * TheCoin simple broker services.  This sample API is an example of how to setup the simplest low-volume exchange, when combined with the included server code, without external dependencies
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SellRequest model module.
 * @module model/SellRequest
 * @version 0.1.0
 */
class SellRequest {
    /**
     * Constructs a new <code>SellRequest</code>.
     * @alias module:model/SellRequest
     * @param email {String} 
     * @param txHash {String} 
     */
    constructor(email, txHash) { 
        
        SellRequest.initialize(this, email, txHash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, txHash) { 
        obj['email'] = email;
        obj['txHash'] = txHash;
    }

    /**
     * Constructs a <code>SellRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SellRequest} obj Optional instance to populate.
     * @return {module:model/SellRequest} The populated <code>SellRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('txHash')) {
                obj['txHash'] = ApiClient.convertToType(data['txHash'], 'String');
            }
            if (data.hasOwnProperty('blockNumber')) {
                obj['blockNumber'] = ApiClient.convertToType(data['blockNumber'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
SellRequest.prototype['email'] = undefined;

/**
 * @member {String} txHash
 */
SellRequest.prototype['txHash'] = undefined;

/**
 * @member {Number} blockNumber
 */
SellRequest.prototype['blockNumber'] = undefined;






export default SellRequest;

