/**
 * TheCoin Core
 * TheCoin core services.  Published by TheCoin Tech
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FXRate model module.
 * @module model/FXRate
 * @version 0.1.0
 */
class FXRate {
    /**
     * Constructs a new <code>FXRate</code>.
     * @alias module:model/FXRate
     * @param buy {Number} 
     * @param sell {Number} 
     * @param fxRate {Number} 
     * @param validFrom {Number} 
     * @param validTill {Number} 
     */
    constructor(buy, sell, fxRate, validFrom, validTill) { 
        
        FXRate.initialize(this, buy, sell, fxRate, validFrom, validTill);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, buy, sell, fxRate, validFrom, validTill) { 
        obj['Buy'] = buy;
        obj['Sell'] = sell;
        obj['FxRate'] = fxRate;
        obj['ValidFrom'] = validFrom;
        obj['ValidTill'] = validTill;
    }

    /**
     * Constructs a <code>FXRate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FXRate} obj Optional instance to populate.
     * @return {module:model/FXRate} The populated <code>FXRate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FXRate();

            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'Number');
            }
            if (data.hasOwnProperty('Buy')) {
                obj['Buy'] = ApiClient.convertToType(data['Buy'], 'Number');
            }
            if (data.hasOwnProperty('Sell')) {
                obj['Sell'] = ApiClient.convertToType(data['Sell'], 'Number');
            }
            if (data.hasOwnProperty('FxRate')) {
                obj['FxRate'] = ApiClient.convertToType(data['FxRate'], 'Number');
            }
            if (data.hasOwnProperty('ValidFrom')) {
                obj['ValidFrom'] = ApiClient.convertToType(data['ValidFrom'], 'Number');
            }
            if (data.hasOwnProperty('ValidTill')) {
                obj['ValidTill'] = ApiClient.convertToType(data['ValidTill'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} target
 */
FXRate.prototype['target'] = undefined;

/**
 * @member {Number} Buy
 */
FXRate.prototype['Buy'] = undefined;

/**
 * @member {Number} Sell
 */
FXRate.prototype['Sell'] = undefined;

/**
 * @member {Number} FxRate
 */
FXRate.prototype['FxRate'] = undefined;

/**
 * @member {Number} ValidFrom
 */
FXRate.prototype['ValidFrom'] = undefined;

/**
 * @member {Number} ValidTill
 */
FXRate.prototype['ValidTill'] = undefined;






export default FXRate;

