// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'link': string;
  'menu': string;
  'ui': string;
}
declare var cssExports: CssExports;
export = cssExports;
