/* 
 * TheCoin Broker
 *
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = TapCap.Client.Client.SwaggerDateConverter;

namespace TapCap.Client.Model
{
    /// <summary>
    /// TapCapHistoryResponseSigned
    /// </summary>
    [DataContract]
    public partial class TapCapHistoryResponseSigned :  IEquatable<TapCapHistoryResponseSigned>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapHistoryResponseSigned" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TapCapHistoryResponseSigned() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapHistoryResponseSigned" /> class.
        /// </summary>
        /// <param name="Response">Response (required).</param>
        /// <param name="Signature">Signature (required).</param>
        public TapCapHistoryResponseSigned(TapCapHistoryResponse Response = default(TapCapHistoryResponse), string Signature = default(string))
        {
            // to ensure "Response" is required (not null)
            if (Response == null)
            {
                throw new InvalidDataException("Response is a required property for TapCapHistoryResponseSigned and cannot be null");
            }
            else
            {
                this.Response = Response;
            }
            // to ensure "Signature" is required (not null)
            if (Signature == null)
            {
                throw new InvalidDataException("Signature is a required property for TapCapHistoryResponseSigned and cannot be null");
            }
            else
            {
                this.Signature = Signature;
            }
        }
        
        /// <summary>
        /// Gets or Sets Response
        /// </summary>
        [DataMember(Name="response", EmitDefaultValue=false)]
        public TapCapHistoryResponse Response { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TapCapHistoryResponseSigned {\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TapCapHistoryResponseSigned);
        }

        /// <summary>
        /// Returns true if TapCapHistoryResponseSigned instances are equal
        /// </summary>
        /// <param name="input">Instance of TapCapHistoryResponseSigned to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TapCapHistoryResponseSigned input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Response == input.Response ||
                    (this.Response != null &&
                    this.Response.Equals(input.Response))
                ) && 
                (
                    this.Signature == input.Signature ||
                    (this.Signature != null &&
                    this.Signature.Equals(input.Signature))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Response != null)
                    hashCode = hashCode * 59 + this.Response.GetHashCode();
                if (this.Signature != null)
                    hashCode = hashCode * 59 + this.Signature.GetHashCode();
                return hashCode;
            }
        }
    }

}
