---
swagger: "2.0"
info:
  description: "TheCoin core services.  Published by TheCoin Tech"
  version: "0.1.0"
  title: "TheCoin Core"
  contact:
    email: "stephen.taylor.dev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "thecoincore-210819.appspot.com"
tags:
- name: "Rates"
  description: "The Coin exchange rates service.  This service provides the official\
    \ rates"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /rates/{currencyCode}:
    get:
      tags:
      - "Rates"
      summary: "Exchange Rate"
      description: "Query exchange rate for THE into the given currency"
      operationId: "getConversion"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "currencyCode"
        in: "path"
        description: "The integer code for the countries currency"
        required: true
        type: "integer"
      - name: "timestamp"
        in: "query"
        description: "The timestamp we are requesting valid values for"
        required: true
        type: "integer"
      responses:
        200:
          description: "TheCoin exchange multiplier to the listed currency"
          schema:
            $ref: "#/definitions/inline_response_200"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Rates"
definitions:
  inline_response_200:
    required:
    - "CoinRate"
    - "FxRate"
    - "target"
    properties:
      target:
        type: "integer"
        format: "int64"
      CoinRate:
        type: "number"
        format: "double"
      FxRate:
        type: "number"
        format: "double"
    example:
      CoinRate: 6.02745618307040320615897144307382404804229736328125
      FxRate: 1.46581298050294517310021547018550336360931396484375
      target: 0
