/* 
 * The TapCap Manager
 *
 * The TapCap resolution.  This service is the trusted 3rd party that weekly settles TapCap purchases
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = TapCapManager.Client.Client.OpenAPIDateConverter;

namespace TapCapManager.Client.Model
{
    /// <summary>
    /// TapCapBrokerComplete
    /// </summary>
    [DataContract]
    public partial class TapCapBrokerComplete :  IEquatable<TapCapBrokerComplete>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapBrokerComplete" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TapCapBrokerComplete() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapBrokerComplete" /> class.
        /// </summary>
        /// <param name="signedRequest">signedRequest (required).</param>
        /// <param name="fxRate">fxRate (required).</param>
        /// <param name="coinCharge">coinCharge (required).</param>
        /// <param name="merchantId">merchantId (required).</param>
        public TapCapBrokerComplete(SignedMessage signedRequest = default(SignedMessage), FXRate fxRate = default(FXRate), long? coinCharge = default(long?), string merchantId = default(string))
        {
            // to ensure "signedRequest" is required (not null)
            if (signedRequest == null)
            {
                throw new InvalidDataException("signedRequest is a required property for TapCapBrokerComplete and cannot be null");
            }
            else
            {
                this.SignedRequest = signedRequest;
            }
            // to ensure "fxRate" is required (not null)
            if (fxRate == null)
            {
                throw new InvalidDataException("fxRate is a required property for TapCapBrokerComplete and cannot be null");
            }
            else
            {
                this.FxRate = fxRate;
            }
            // to ensure "coinCharge" is required (not null)
            if (coinCharge == null)
            {
                throw new InvalidDataException("coinCharge is a required property for TapCapBrokerComplete and cannot be null");
            }
            else
            {
                this.CoinCharge = coinCharge;
            }
            // to ensure "merchantId" is required (not null)
            if (merchantId == null)
            {
                throw new InvalidDataException("merchantId is a required property for TapCapBrokerComplete and cannot be null");
            }
            else
            {
                this.MerchantId = merchantId;
            }
        }
        
        /// <summary>
        /// Gets or Sets SignedRequest
        /// </summary>
        [DataMember(Name="signedRequest", EmitDefaultValue=false)]
        public SignedMessage SignedRequest { get; set; }

        /// <summary>
        /// Gets or Sets FxRate
        /// </summary>
        [DataMember(Name="FxRate", EmitDefaultValue=false)]
        public FXRate FxRate { get; set; }

        /// <summary>
        /// Gets or Sets CoinCharge
        /// </summary>
        [DataMember(Name="coinCharge", EmitDefaultValue=false)]
        public long? CoinCharge { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name="merchantId", EmitDefaultValue=false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TapCapBrokerComplete {\n");
            sb.Append("  SignedRequest: ").Append(SignedRequest).Append("\n");
            sb.Append("  FxRate: ").Append(FxRate).Append("\n");
            sb.Append("  CoinCharge: ").Append(CoinCharge).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TapCapBrokerComplete);
        }

        /// <summary>
        /// Returns true if TapCapBrokerComplete instances are equal
        /// </summary>
        /// <param name="input">Instance of TapCapBrokerComplete to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TapCapBrokerComplete input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SignedRequest == input.SignedRequest ||
                    (this.SignedRequest != null &&
                    this.SignedRequest.Equals(input.SignedRequest))
                ) && 
                (
                    this.FxRate == input.FxRate ||
                    (this.FxRate != null &&
                    this.FxRate.Equals(input.FxRate))
                ) && 
                (
                    this.CoinCharge == input.CoinCharge ||
                    (this.CoinCharge != null &&
                    this.CoinCharge.Equals(input.CoinCharge))
                ) && 
                (
                    this.MerchantId == input.MerchantId ||
                    (this.MerchantId != null &&
                    this.MerchantId.Equals(input.MerchantId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignedRequest != null)
                    hashCode = hashCode * 59 + this.SignedRequest.GetHashCode();
                if (this.FxRate != null)
                    hashCode = hashCode * 59 + this.FxRate.GetHashCode();
                if (this.CoinCharge != null)
                    hashCode = hashCode * 59 + this.CoinCharge.GetHashCode();
                if (this.MerchantId != null)
                    hashCode = hashCode * 59 + this.MerchantId.GetHashCode();
                return hashCode;
            }
        }
    }

}
