/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

import type { DateTime } from "luxon";

export interface SignedMessage {
  message: string;
  signature: string;
}
export interface GoogleWalletItem {
  id: GoogleFileIdent;
  wallet?: string;
}
export interface GoogleToken {
  token: string;
}
export interface GoogleStoreAccount {
  token: GoogleToken;
  wallet: string;
  walletName: string;
}
export interface GoogleListResult {
  wallets: GoogleFileIdent[];
}
export interface GoogleGetResult {
  wallets: GoogleWalletItem[];
}
export interface GoogleFileIdent {
  id: string;
  name?: string;
  type?: string;
}
export interface GoogleAuthUrl {
  url: string;
}
export interface ETransferPacket {
  email: string;
  question: string;
  answer: string;
  message?: string;
}
export interface EncryptedPacket {
  encryptedPacket: string;
  version: string;
}

// IMPORTANT: Any changes to this structure requires
// updating the matching isCertTransfer function
export interface CertifiedTransferRequest {
  chainId: number;
  from: string;
  to: string;
  value: number;
  fee: number;
  timestamp: number;
  signature: string;
}
export interface CertifiedTransfer {
  transfer: CertifiedTransferRequest;
  instructionPacket: EncryptedPacket;
  signature: string;
}

// IMPORTANT: Any changes to this structure requires
// updating the matching isUberTransfer function
export type UberTransfer = {
  chainId: number;
  from: string,
  to: string,
  amount: number,
  currency: number,
  transferMillis: number,
  signedMillis: number,
  signature: string,
}

export type UberTransferAction = {
  transfer: UberTransfer,
  instructionPacket: EncryptedPacket,
  signature: string,
}

export type AnyTransfer = CertifiedTransferRequest | UberTransfer;

export interface BrokerStatus {
  address: string;
  certifiedFee: number;
}
export interface BillPayeePacket {
  payee: string;
  accountNumber: string;
}

export type AssignPluginRequest = {
  chainId: number;
  user: string;
  plugin: string;
  permissions: string;
  timeMs: DateTime;
  signedAt: DateTime;
  signature: string;
}

export type RemovePluginRequest = {
  user: string;
  chainId: number;
  index: number;
  signedAt: DateTime;
  signature: string;
}

export type ConnectionValues = {
  state: string;
  siteOrigin: string;
  timestamp: string;
  address: string;
  name: string;
  walletFile: string;
  phrase: string;
  path: string;
  locale: string;
}
