// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerImage': string;
  'headerLogo': string;
  'headerText': string;
  'inflation': string;
  'wallStreet': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
