/*
 * THE TapCap supply
 *
 * The interace for TapCap between buyers & sellers.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace TapCapSupplier.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class QueryWithHistory : IEquatable<QueryWithHistory>
    { 
        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [Required]
        [DataMember(Name="query")]
        public byte[] Query { get; set; }

        /// <summary>
        /// Gets or Sets Queries
        /// </summary>
        [Required]
        [DataMember(Name="queries")]
        public List<byte[]> Queries { get; set; }

        /// <summary>
        /// Gets or Sets Responses
        /// </summary>
        [Required]
        [DataMember(Name="responses")]
        public List<byte[]> Responses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryWithHistory {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("  Responses: ").Append(Responses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((QueryWithHistory)obj);
        }

        /// <summary>
        /// Returns true if QueryWithHistory instances are equal
        /// </summary>
        /// <param name="other">Instance of QueryWithHistory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryWithHistory other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Query == other.Query ||
                    Query != null &&
                    Query.Equals(other.Query)
                ) && 
                (
                    Queries == other.Queries ||
                    Queries != null &&
                    Queries.SequenceEqual(other.Queries)
                ) && 
                (
                    Responses == other.Responses ||
                    Responses != null &&
                    Responses.SequenceEqual(other.Responses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Query != null)
                    hashCode = hashCode * 59 + Query.GetHashCode();
                    if (Queries != null)
                    hashCode = hashCode * 59 + Queries.GetHashCode();
                    if (Responses != null)
                    hashCode = hashCode * 59 + Responses.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(QueryWithHistory left, QueryWithHistory right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(QueryWithHistory left, QueryWithHistory right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
