/* 
 * TheCoin Core
 *
 * TheCoin pricing service.  Published by TheCoin Tech
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using ThePricing.Client;
using ThePricing.Model;

namespace ThePricing.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRatesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Exchange Rate
        /// </summary>
        /// <remarks>
        /// Query exchange rate for THE into the given currency
        /// </remarks>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>FXRate</returns>
        FXRate GetConversion (int? currencyCode, long? timestamp);

        /// <summary>
        /// Exchange Rate
        /// </summary>
        /// <remarks>
        /// Query exchange rate for THE into the given currency
        /// </remarks>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>ApiResponse of FXRate</returns>
        ApiResponse<FXRate> GetConversionWithHttpInfo (int? currencyCode, long? timestamp);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Exchange Rate
        /// </summary>
        /// <remarks>
        /// Query exchange rate for THE into the given currency
        /// </remarks>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>Task of FXRate</returns>
        System.Threading.Tasks.Task<FXRate> GetConversionAsync (int? currencyCode, long? timestamp);

        /// <summary>
        /// Exchange Rate
        /// </summary>
        /// <remarks>
        /// Query exchange rate for THE into the given currency
        /// </remarks>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>Task of ApiResponse (FXRate)</returns>
        System.Threading.Tasks.Task<ApiResponse<FXRate>> GetConversionAsyncWithHttpInfo (int? currencyCode, long? timestamp);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RatesApi : IRatesApi
    {
        private ThePricing.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RatesApi(String basePath)
        {
            this.Configuration = new ThePricing.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ThePricing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RatesApi(ThePricing.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ThePricing.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ThePricing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ThePricing.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ThePricing.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Exchange Rate Query exchange rate for THE into the given currency
        /// </summary>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>FXRate</returns>
        public FXRate GetConversion (int? currencyCode, long? timestamp)
        {
             ApiResponse<FXRate> localVarResponse = GetConversionWithHttpInfo(currencyCode, timestamp);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Exchange Rate Query exchange rate for THE into the given currency
        /// </summary>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>ApiResponse of FXRate</returns>
        public ApiResponse< FXRate > GetConversionWithHttpInfo (int? currencyCode, long? timestamp)
        {
            // verify the required parameter 'currencyCode' is set
            if (currencyCode == null)
                throw new ApiException(400, "Missing required parameter 'currencyCode' when calling RatesApi->GetConversion");
            // verify the required parameter 'timestamp' is set
            if (timestamp == null)
                throw new ApiException(400, "Missing required parameter 'timestamp' when calling RatesApi->GetConversion");

            var localVarPath = "./rates/{currencyCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currencyCode != null) localVarPathParams.Add("currencyCode", this.Configuration.ApiClient.ParameterToString(currencyCode)); // path parameter
            if (timestamp != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "timestamp", timestamp)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetConversion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FXRate>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (FXRate) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FXRate)));
        }

        /// <summary>
        /// Exchange Rate Query exchange rate for THE into the given currency
        /// </summary>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>Task of FXRate</returns>
        public async System.Threading.Tasks.Task<FXRate> GetConversionAsync (int? currencyCode, long? timestamp)
        {
             ApiResponse<FXRate> localVarResponse = await GetConversionAsyncWithHttpInfo(currencyCode, timestamp);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Exchange Rate Query exchange rate for THE into the given currency
        /// </summary>
        /// <exception cref="ThePricing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currencyCode">The integer code for the countries currency</param>
        /// <param name="timestamp">The timestamp we are requesting valid values for</param>
        /// <returns>Task of ApiResponse (FXRate)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<FXRate>> GetConversionAsyncWithHttpInfo (int? currencyCode, long? timestamp)
        {
            // verify the required parameter 'currencyCode' is set
            if (currencyCode == null)
                throw new ApiException(400, "Missing required parameter 'currencyCode' when calling RatesApi->GetConversion");
            // verify the required parameter 'timestamp' is set
            if (timestamp == null)
                throw new ApiException(400, "Missing required parameter 'timestamp' when calling RatesApi->GetConversion");

            var localVarPath = "./rates/{currencyCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currencyCode != null) localVarPathParams.Add("currencyCode", this.Configuration.ApiClient.ParameterToString(currencyCode)); // path parameter
            if (timestamp != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "timestamp", timestamp)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetConversion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FXRate>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (FXRate) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FXRate)));
        }

    }
}
