/* 
 * THE TapCap supply
 *
 * The interace for TapCap between buyers & sellers.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = TapCap.Supplier.Client.OpenAPIDateConverter;

namespace TapCap.Supplier.Model
{
    /// <summary>
    /// TapCapRequest
    /// </summary>
    [DataContract]
    public partial class TapCapRequest :  IEquatable<TapCapRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TapCapRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TapCapRequest" /> class.
        /// </summary>
        /// <param name="timestamp">timestamp (required).</param>
        /// <param name="fiatAmount">fiatAmount (required).</param>
        /// <param name="currencyCode">currencyCode (required).</param>
        /// <param name="gpoPdol">gpoPdol (required).</param>
        /// <param name="cryptoPdol">cryptoPdol (required).</param>
        /// <param name="token">token (required).</param>
        public TapCapRequest(double? timestamp = default(double?), double? fiatAmount = default(double?), decimal? currencyCode = default(decimal?), byte[] gpoPdol = default(byte[]), byte[] cryptoPdol = default(byte[]), SignedMessage token = default(SignedMessage))
        {
            // to ensure "timestamp" is required (not null)
            if (timestamp == null)
            {
                throw new InvalidDataException("timestamp is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.Timestamp = timestamp;
            }
            // to ensure "fiatAmount" is required (not null)
            if (fiatAmount == null)
            {
                throw new InvalidDataException("fiatAmount is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.FiatAmount = fiatAmount;
            }
            // to ensure "currencyCode" is required (not null)
            if (currencyCode == null)
            {
                throw new InvalidDataException("currencyCode is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.CurrencyCode = currencyCode;
            }
            // to ensure "gpoPdol" is required (not null)
            if (gpoPdol == null)
            {
                throw new InvalidDataException("gpoPdol is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.GpoPdol = gpoPdol;
            }
            // to ensure "cryptoPdol" is required (not null)
            if (cryptoPdol == null)
            {
                throw new InvalidDataException("cryptoPdol is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.CryptoPdol = cryptoPdol;
            }
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new InvalidDataException("token is a required property for TapCapRequest and cannot be null");
            }
            else
            {
                this.Token = token;
            }
        }
        
        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public double? Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets FiatAmount
        /// </summary>
        [DataMember(Name="fiatAmount", EmitDefaultValue=false)]
        public double? FiatAmount { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyCode
        /// </summary>
        [DataMember(Name="currencyCode", EmitDefaultValue=false)]
        public decimal? CurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets GpoPdol
        /// </summary>
        [DataMember(Name="gpoPdol", EmitDefaultValue=false)]
        public byte[] GpoPdol { get; set; }

        /// <summary>
        /// Gets or Sets CryptoPdol
        /// </summary>
        [DataMember(Name="cryptoPdol", EmitDefaultValue=false)]
        public byte[] CryptoPdol { get; set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [DataMember(Name="token", EmitDefaultValue=false)]
        public SignedMessage Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TapCapRequest {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  FiatAmount: ").Append(FiatAmount).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  GpoPdol: ").Append(GpoPdol).Append("\n");
            sb.Append("  CryptoPdol: ").Append(CryptoPdol).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TapCapRequest);
        }

        /// <summary>
        /// Returns true if TapCapRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TapCapRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TapCapRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.FiatAmount == input.FiatAmount ||
                    (this.FiatAmount != null &&
                    this.FiatAmount.Equals(input.FiatAmount))
                ) && 
                (
                    this.CurrencyCode == input.CurrencyCode ||
                    (this.CurrencyCode != null &&
                    this.CurrencyCode.Equals(input.CurrencyCode))
                ) && 
                (
                    this.GpoPdol == input.GpoPdol ||
                    (this.GpoPdol != null &&
                    this.GpoPdol.Equals(input.GpoPdol))
                ) && 
                (
                    this.CryptoPdol == input.CryptoPdol ||
                    (this.CryptoPdol != null &&
                    this.CryptoPdol.Equals(input.CryptoPdol))
                ) && 
                (
                    this.Token == input.Token ||
                    (this.Token != null &&
                    this.Token.Equals(input.Token))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.FiatAmount != null)
                    hashCode = hashCode * 59 + this.FiatAmount.GetHashCode();
                if (this.CurrencyCode != null)
                    hashCode = hashCode * 59 + this.CurrencyCode.GetHashCode();
                if (this.GpoPdol != null)
                    hashCode = hashCode * 59 + this.GpoPdol.GetHashCode();
                if (this.CryptoPdol != null)
                    hashCode = hashCode * 59 + this.CryptoPdol.GetHashCode();
                if (this.Token != null)
                    hashCode = hashCode * 59 + this.Token.GetHashCode();
                return hashCode;
            }
        }
    }

}
