/**
 * The TapCap Manager
 * The TapCap resolution.  This service is the trusted 3rd party that weekly settles TapCap purchases
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TapCapToken model module.
 * @module model/TapCapToken
 * @version 0.0.1
 */
class TapCapToken {
    /**
     * Constructs a new <code>TapCapToken</code>.
     * @alias module:model/TapCapToken
     * @param clientAccount {String} 
     * @param availableBalance {Number} 
     * @param transactionId {Number} 
     * @param timestamp {Number} 
     */
    constructor(clientAccount, availableBalance, transactionId, timestamp) { 
        
        TapCapToken.initialize(this, clientAccount, availableBalance, transactionId, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clientAccount, availableBalance, transactionId, timestamp) { 
        obj['clientAccount'] = clientAccount;
        obj['availableBalance'] = availableBalance;
        obj['transactionId'] = transactionId;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>TapCapToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TapCapToken} obj Optional instance to populate.
     * @return {module:model/TapCapToken} The populated <code>TapCapToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapToken();

            if (data.hasOwnProperty('clientAccount')) {
                obj['clientAccount'] = ApiClient.convertToType(data['clientAccount'], 'String');
            }
            if (data.hasOwnProperty('availableBalance')) {
                obj['availableBalance'] = ApiClient.convertToType(data['availableBalance'], 'Number');
            }
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} clientAccount
 */
TapCapToken.prototype['clientAccount'] = undefined;

/**
 * @member {Number} availableBalance
 */
TapCapToken.prototype['availableBalance'] = undefined;

/**
 * @member {Number} transactionId
 */
TapCapToken.prototype['transactionId'] = undefined;

/**
 * @member {Number} timestamp
 */
TapCapToken.prototype['timestamp'] = undefined;






export default TapCapToken;

