/**
 * The TapCap Manager
 * The TapCap resolution.  This service is the trusted 3rd party that weekly settles TapCap purchases
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SignedMessage from './SignedMessage';

/**
 * The TapCapClientRequest model module.
 * @module model/TapCapClientRequest
 * @version 0.0.1
 */
class TapCapClientRequest {
    /**
     * Constructs a new <code>TapCapClientRequest</code>.
     * @alias module:model/TapCapClientRequest
     * @param timestamp {Number} 
     * @param gpoData {Blob} 
     * @param cryptoData {Blob} 
     * @param supplierAddress {String} 
     * @param token {module:model/SignedMessage} 
     */
    constructor(timestamp, gpoData, cryptoData, supplierAddress, token) { 
        
        TapCapClientRequest.initialize(this, timestamp, gpoData, cryptoData, supplierAddress, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timestamp, gpoData, cryptoData, supplierAddress, token) { 
        obj['timestamp'] = timestamp;
        obj['gpoData'] = gpoData;
        obj['cryptoData'] = cryptoData;
        obj['supplierAddress'] = supplierAddress;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>TapCapClientRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TapCapClientRequest} obj Optional instance to populate.
     * @return {module:model/TapCapClientRequest} The populated <code>TapCapClientRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapClientRequest();

            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('gpoData')) {
                obj['gpoData'] = ApiClient.convertToType(data['gpoData'], 'Blob');
            }
            if (data.hasOwnProperty('cryptoData')) {
                obj['cryptoData'] = ApiClient.convertToType(data['cryptoData'], 'Blob');
            }
            if (data.hasOwnProperty('supplierAddress')) {
                obj['supplierAddress'] = ApiClient.convertToType(data['supplierAddress'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = SignedMessage.constructFromObject(data['token']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} timestamp
 */
TapCapClientRequest.prototype['timestamp'] = undefined;

/**
 * @member {Blob} gpoData
 */
TapCapClientRequest.prototype['gpoData'] = undefined;

/**
 * @member {Blob} cryptoData
 */
TapCapClientRequest.prototype['cryptoData'] = undefined;

/**
 * @member {String} supplierAddress
 */
TapCapClientRequest.prototype['supplierAddress'] = undefined;

/**
 * @member {module:model/SignedMessage} token
 */
TapCapClientRequest.prototype['token'] = undefined;






export default TapCapClientRequest;

