/**
 * TheCoin Broker
 * TheCoin TapCap resolution.  This service is the trusted 3rd party that weekly settles TapCap purchases
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageSigned from './MessageSigned';

/**
 * The TapCapPurchase model module.
 * @module model/TapCapPurchase
 * @version 0.0.1
 */
class TapCapPurchase {
    /**
     * Constructs a new <code>TapCapPurchase</code>.
     * @alias module:model/TapCapPurchase
     * @param fiat {Number} 
     * @param currencyCode {Number} 
     * @param timestamp {Number} 
     * @param gpoData {Blob} 
     * @param certificateRequest {Blob} 
     * @param token {module:model/MessageSigned} 
     */
    constructor(fiat, currencyCode, timestamp, gpoData, certificateRequest, token) { 
        
        TapCapPurchase.initialize(this, fiat, currencyCode, timestamp, gpoData, certificateRequest, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fiat, currencyCode, timestamp, gpoData, certificateRequest, token) { 
        obj['fiat'] = fiat;
        obj['currencyCode'] = currencyCode;
        obj['timestamp'] = timestamp;
        obj['gpoData'] = gpoData;
        obj['certificateRequest'] = certificateRequest;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>TapCapPurchase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TapCapPurchase} obj Optional instance to populate.
     * @return {module:model/TapCapPurchase} The populated <code>TapCapPurchase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapPurchase();

            if (data.hasOwnProperty('fiat')) {
                obj['fiat'] = ApiClient.convertToType(data['fiat'], 'Number');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('gpoData')) {
                obj['gpoData'] = ApiClient.convertToType(data['gpoData'], 'Blob');
            }
            if (data.hasOwnProperty('certificateRequest')) {
                obj['certificateRequest'] = ApiClient.convertToType(data['certificateRequest'], 'Blob');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = MessageSigned.constructFromObject(data['token']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} fiat
 */
TapCapPurchase.prototype['fiat'] = undefined;

/**
 * @member {Number} currencyCode
 */
TapCapPurchase.prototype['currencyCode'] = undefined;

/**
 * @member {Number} timestamp
 */
TapCapPurchase.prototype['timestamp'] = undefined;

/**
 * @member {Blob} gpoData
 */
TapCapPurchase.prototype['gpoData'] = undefined;

/**
 * @member {Blob} certificateRequest
 */
TapCapPurchase.prototype['certificateRequest'] = undefined;

/**
 * @member {module:model/MessageSigned} token
 */
TapCapPurchase.prototype['token'] = undefined;






export default TapCapPurchase;

