swagger: "2.0"
info:
  description: "TheCoin broker services.  To be implemented allowing exchange of local currency to THESE"
  version: "0.0.1"
  title: "TheCoin Broker"
  contact:
    email: "stephen.taylor.dev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.222.141.84:29554"
tags:
- name: "The"
  description: "The Coin: TapCap manager is responsible for resolving TapCap transactions, and tracking user TapCap accounts"
  externalDocs:
    description: "Find out more"
    url: "http://192.222.141.84/docs"
schemes:
- "https"

definitions:

  # A token may be presented to a broker
  # as proof of funds.  If signed by the
  # broker, it indicates the client is trusted
  # and sufficient balance to cover the
  # available balance listed here.
  TapCapToken:
    required:
      - clientAccount
      - availableBalance
      - transactionId
      - timestamp
    properties:
      clientAccount:
        type: string
      availableBalance:
        type: number
        format: int64    
      transactionId:
        type: number
      # The timestamp of issue.  A broker
      # may ignore a token if the timestamp is too old
      timestamp:
        type: number
        format: int64

  # A token signed by the TapCapManager
  TapCapTokenSigned:
    required:
      - token
      - signature
    properties:
      token:
        $ref: "#/definitions/TapCapToken"
      signature:
        type: string

  # A purchase request is sent to a broker.  If
  # the broker satisfies the request, the signed
  # purchase structure may be forwarded to the
  # manager for settlement
  TapCapPurchase:
    required:
      - fiat
      - currencyCode
      - timestamp
      - token # Every successful transaction ibcrements this number
    properties:
      fiat:
        type: number
      currencyCode:
        type: number
      timestamp:  # Only requests in the past X seconds will be acccepted?  Security risk here?
        type: number
        format: int64
      token:
        $ref: "#/definitions/TapCapTokenSigned"

  # A client signs the initial purchase request
  # and sends this request to the Broker
  TapCapPurchaseSigned:
    required:
      - request
      - signature
    properties:
      request:
        $ref: "#/definitions/TapCapPurchase"
      signature:
        type: string

  # If the broker accepts the request, they generate
  # this response structure, fill out the fields and
  # return to the client.
  TapCapPurchaseBroker:
    required:
      - request
      - coin
      - cert
    properties:
      request:
        $ref: "#/definitions/TapCapPurchaseSigned"
      coin:  # The amount of coin being charged for this transaction
        type: number
        format: int64
      cert:
        type: string

  # The broker signs the return structure to 
  # guarantee the purchase will be successful
  TapCapPurchaseBrokerSigned:
    required:
      - response
      - signature
    properties:
      request:
        $ref: "#/definitions/TapCapPurchaseBroker"
      signature:
        type: string

  # ---------------------------------------------------------------- #

  # Query the Manager for a clients TapCap balance  
  TapCapQueryRequest:
    required:
    - timestamp
    - random
    properties:
      timestamp:  # Only requests in the past  seconds will be acccepted?  Security risk here?
        type: number
        format: int64
      random:     # Randomly generated by client.  Only used to validate the signature
        type: string

  # Signed request ensures it could only have come
  # from the client
  TapCapQueryRequestSigned:
    required:
      - request
      - signature
    properties:
      request:
        $ref: "#/definitions/TapCapQueryRequest"
      signature:
        type: string

  # basic stats 
  TapCapQueryResponse:
    required:
    - balance
    - weeklyTopup
    properties:
      balance:
        type: number
        format: int64
      weeklyTopup:
        type: number
        format: int64

  TapCapQueryResponseSigned:
    required:
      - response
      - signature
    properties:
      response:
        $ref: "#/definitions/TapCapQueryResponse"
      signature:
        type: string

  TapCapHistoryRequest:
    required:
    - fromTimestamp
    - untilTimestamp
    - msgTimestamp 
    properties:
      fromTimestamp:
        type: number
        format: int64
      untilTimestamp:
        type: number
        format: int64
      # Only requests from the preceding 5 seconds will be fullfilled.
      # This prevents someone copying/cloning a message and using repeating it later.
      msgTimestamp:
        type: number
        format: int64

  TapCapHistoryRequestSigned:
    required:
      - request
      - signature
    properties:
      request:
        $ref: "#/definitions/TapCapHistoryRequest"
      signature:
        type: string
        
  TapCapTransaction:
    required:
      - timestamp
      - fiatAmount
      - coinAmount
      - coinBalance
      - merchantId
    properties:
      timestamp:
        type: number
        format: int64
      fiatAmount:
        type: number
        format: double
      coinAmount:
        type: number
        format: int64
      merchantId:
        type: string

  TapCapHistoryResponse:
    required:
      - history
    properties:
      history:
        type: array
        items:
          $ref: "#/definitions/TapCapTransaction"

  TapCapHistoryResponseSigned:
    required:
      - response
      - signature
    properties:
      response:
        $ref: "#/definitions/TapCapHistoryResponse"
      signature:
        type: string          

# ---------------------------------------------------------------- #

consumes:
  - application/json
produces:
  - application/json

paths:
  /tap/broker:
    post:
      tags:
        - Transactions
      summary: "Broker: Register new TapCap transaction"
      operationId: "TapCapBroker"
      responses:
        405:
          description: "Invalid input"
        200:
          description: TapCap Status
          schema:
            $ref: "#/definitions/TapCapQueryResponseSigned"

      parameters:
        - in: body
          name: request
          description: "TapCap status request"
          required: true
          schema: 
            $ref: "#/definitions/TapCapPurchaseBrokerSigned"

  /tap/client: 
    post:
      tags:
        - Transactions
      summary: "Client: Confirm new TapCap transaction"
      operationId: "TapCapClient"
      responses:
        405:
          description: "Invalid input"
        200:
          description: "TapCap Token valid for the next purchase"
          schema:
            $ref: "#/definitions/TapCapPurchaseSigned"

      parameters:
        - in: body
          name: request
          description: "TapCap status request"
          required: true
          schema: 
            $ref: "#/definitions/TapCapTokenSigned"
  /tap/state:
    post:
      tags: 
        - TapCap
      summary: "TapCap current status"
      description: "User TapCap status"
      operationId: "TapCapStatus"
      responses:
        405:
          description: "Invalid input"
        200:
          description: TapCap Status
          schema:
            $ref: "#/definitions/TapCapQueryResponseSigned"

      parameters:
        - in: body
          name: request
          description: "TapCap status request"
          required: true
          schema: 
            $ref: "#/definitions/TapCapQueryRequestSigned"

  /tap/history:
    post:
      tags:
        - TapCap
      summary: "TapCap current status"
      description: "User TapCap status"
      operationId: "TapCapHistory"
      parameters:
        - in: body
          name: request
          description: "Purchase Request info"
          required: true
          schema: 
            $ref: "#/definitions/TapCapHistoryRequestSigned"
      responses:
        405:
          description: "Invalid input"
        200:
          description: TapCap Status
          schema:
            $ref: "#/definitions/TapCapHistoryResponseSigned"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"