---
swagger: "2.0"
info:
  description: "TheCoin TapCap resolution.  This service is the trusted 3rd party\
    \ that weekly settles TapCap purchases"
  version: "0.0.1"
  title: "TheCoin Broker"
  contact:
    email: "stephen.taylor.dev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "Transactions"
  description: "The Coin: TapCap manager is responsible for resolving TapCap transactions,\
    \ transfering the appropriate coin from seller to buyer weekly"
- name: "Status"
  description: "Users may query their account status"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /tap/broker:
    post:
      tags:
      - "Transactions"
      summary: "Broker: Register new TapCap transaction"
      operationId: "TapCapBroker"
      parameters:
      - in: "body"
        name: "request"
        description: "TapCap exchange request"
        required: true
        schema:
          $ref: "#/definitions/MessageSigned"
      responses:
        200:
          description: "Transaction Result"
          schema:
            $ref: "#/definitions/inline_response_200"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Transactions"
  /tap/client:
    post:
      tags:
      - "Transactions"
      summary: "Client: Confirm new TapCap transaction"
      operationId: "TapCapClient"
      parameters:
      - in: "body"
        name: "request"
        description: "TapCap status request"
        required: true
        schema:
          $ref: "#/definitions/MessageSigned"
      responses:
        200:
          description: "TapCap Token valid for the next purchase"
          schema:
            $ref: "#/definitions/MessageSigned"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Transactions"
  /status/summary:
    post:
      tags:
      - "Status"
      summary: "TapCap current status"
      description: "User TapCap status"
      operationId: "TapCapStatus"
      parameters:
      - in: "body"
        name: "request"
        description: "TapCap status request"
        required: true
        schema:
          $ref: "#/definitions/MessageSigned"
      responses:
        200:
          description: "TapCap Status"
          schema:
            $ref: "#/definitions/TapCapQueryResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Status"
  /status/history:
    post:
      tags:
      - "Status"
      summary: "TapCap history"
      description: "User TapCap history in the ranges provided"
      operationId: "TapCapHistory"
      parameters:
      - in: "body"
        name: "request"
        description: "Purchase Request info"
        required: true
        schema:
          $ref: "#/definitions/MessageSigned"
      responses:
        200:
          description: "TapCap Status"
          schema:
            $ref: "#/definitions/TapCapHistoryResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Status"
definitions:
  MessageSigned:
    required:
    - "signature"
    properties:
      signature:
        type: "string"
    example:
      signature: "signature"
  TapCapToken:
    required:
    - "availableBalance"
    - "clientAccount"
    - "timestamp"
    - "transactionId"
    properties:
      clientAccount:
        type: "string"
      availableBalance:
        type: "number"
        format: "int64"
      transactionId:
        type: "number"
      timestamp:
        type: "number"
        format: "int64"
  TapCapPurchase:
    required:
    - "certificateRequest"
    - "currencyCode"
    - "fiat"
    - "gpoData"
    - "timestamp"
    - "token"
    properties:
      fiat:
        type: "number"
      currencyCode:
        type: "number"
      timestamp:
        type: "number"
        format: "int64"
      gpoData:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
      certificateRequest:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
      token:
        $ref: "#/MessageSigned"
  TapCapPurchaseBroker:
    required:
    - "cert"
    - "clientRequest"
    - "coin"
    properties:
      clientRequest:
        $ref: "#/MessageSigned"
      coin:
        type: "number"
        format: "int64"
      cert:
        type: "string"
  TapCapQueryRequest:
    required:
    - "timestamp"
    properties:
      timestamp:
        type: "number"
        format: "int64"
  TapCapQueryResponse:
    required:
    - "balance"
    - "token"
    - "weeklyTopup"
    properties:
      balance:
        type: "number"
        format: "int64"
      weeklyTopup:
        type: "number"
        format: "int64"
      token:
        $ref: "#/MessageSigned"
    example:
      balance: 0.80082819046101150206595775671303272247314453125
      weeklyTopup: 6.02745618307040320615897144307382404804229736328125
      token:
        signature: "signature"
  TapCapHistoryRequest:
    required:
    - "fromTimestamp"
    - "msgTimestamp"
    - "untilTimestamp"
    properties:
      fromTimestamp:
        type: "number"
        format: "int64"
      untilTimestamp:
        type: "number"
        format: "int64"
      msgTimestamp:
        type: "number"
        format: "int64"
  TapCapTransaction:
    required:
    - "coinAmount"
    - "coinBalance"
    - "fiatAmount"
    - "merchantId"
    - "timestamp"
    properties:
      timestamp:
        type: "number"
        format: "int64"
      fiatAmount:
        type: "number"
        format: "double"
      coinAmount:
        type: "number"
        format: "int64"
      coinBalance:
        type: "number"
        format: "int64"
      merchantId:
        type: "string"
    example:
      coinAmount: 1.46581298050294517310021547018550336360931396484375
      merchantId: "merchantId"
      fiatAmount: 6.02745618307040320615897144307382404804229736328125
      coinBalance: 5.962133916683182377482808078639209270477294921875
      timestamp: 0.80082819046101150206595775671303272247314453125
  TapCapHistoryResponse:
    required:
    - "history"
    properties:
      history:
        type: "array"
        items:
          $ref: "#/TapCapTransaction"
    example:
      history:
      - coinAmount: 1.46581298050294517310021547018550336360931396484375
        merchantId: "merchantId"
        fiatAmount: 6.02745618307040320615897144307382404804229736328125
        coinBalance: 5.962133916683182377482808078639209270477294921875
        timestamp: 0.80082819046101150206595775671303272247314453125
      - coinAmount: 1.46581298050294517310021547018550336360931396484375
        merchantId: "merchantId"
        fiatAmount: 6.02745618307040320615897144307382404804229736328125
        coinBalance: 5.962133916683182377482808078639209270477294921875
        timestamp: 0.80082819046101150206595775671303272247314453125
  inline_response_200:
    required:
    - "errorCode"
    properties:
      errorCode:
        type: "integer"
    example:
      errorCode: 0
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
