---
swagger: "2.0"
info:
  description: "TheCoin pricing service.  Published by TheCoin Tech"
  version: "0.1.0"
  title: "TheCoin Core"
  contact:
    email: "stephen.taylor.dev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "thecoincore-212314.appspot.com"
tags:
- name: "Rates"
  description: "The Coin exchange rates service.  This service provides the official\
    \ rates"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /rates/{currencyCode}:
    get:
      tags:
      - "Rates"
      summary: "Exchange Rate"
      description: "Query exchange rate for THE into the given currency"
      operationId: "getConversion"
      parameters:
      - name: "currencyCode"
        in: "path"
        description: "The integer code for the countries currency"
        required: true
        type: "integer"
      - name: "timestamp"
        in: "query"
        description: "The timestamp we are requesting valid values for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "TheCoin exchange multiplier to the listed currency"
          schema:
            $ref: "#/definitions/FXRate"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Rates"
definitions:
  FXRate:
    required:
    - "buy"
    - "fxRate"
    - "sell"
    - "validFrom"
    - "validTill"
    properties:
      target:
        type: "integer"
      buy:
        type: "number"
        format: "double"
      sell:
        type: "number"
        format: "double"
      fxRate:
        type: "number"
        format: "double"
      validFrom:
        type: "integer"
        format: "int64"
      validTill:
        type: "integer"
        format: "int64"
    example:
      fxRate: 5.962133916683182377482808078639209270477294921875
      validTill: 2
      buy: 6.02745618307040320615897144307382404804229736328125
      sell: 1.46581298050294517310021547018550336360931396484375
      validFrom: 5
      target: 0
