/* 
 * The TapCap Manager
 *
 * The TapCap resolution.  This service is the trusted 3rd party that weekly settles TapCap purchases
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using TapCapManager.Client.Client;
using TapCapManager.Client.Model;

namespace TapCapManager.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatusApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// TapCap history
        /// </summary>
        /// <remarks>
        /// User TapCap history in the ranges provided
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>TapCapHistoryResponse</returns>
        TapCapHistoryResponse TapCapHistory (SignedMessage signedMessage);

        /// <summary>
        /// TapCap history
        /// </summary>
        /// <remarks>
        /// User TapCap history in the ranges provided
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>ApiResponse of TapCapHistoryResponse</returns>
        ApiResponse<TapCapHistoryResponse> TapCapHistoryWithHttpInfo (SignedMessage signedMessage);
        /// <summary>
        /// TapCap current status
        /// </summary>
        /// <remarks>
        /// User TapCap status
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>TapCapQueryResponse</returns>
        TapCapQueryResponse TapCapStatus (SignedMessage signedMessage);

        /// <summary>
        /// TapCap current status
        /// </summary>
        /// <remarks>
        /// User TapCap status
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>ApiResponse of TapCapQueryResponse</returns>
        ApiResponse<TapCapQueryResponse> TapCapStatusWithHttpInfo (SignedMessage signedMessage);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// TapCap history
        /// </summary>
        /// <remarks>
        /// User TapCap history in the ranges provided
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>Task of TapCapHistoryResponse</returns>
        System.Threading.Tasks.Task<TapCapHistoryResponse> TapCapHistoryAsync (SignedMessage signedMessage);

        /// <summary>
        /// TapCap history
        /// </summary>
        /// <remarks>
        /// User TapCap history in the ranges provided
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>Task of ApiResponse (TapCapHistoryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TapCapHistoryResponse>> TapCapHistoryAsyncWithHttpInfo (SignedMessage signedMessage);
        /// <summary>
        /// TapCap current status
        /// </summary>
        /// <remarks>
        /// User TapCap status
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>Task of TapCapQueryResponse</returns>
        System.Threading.Tasks.Task<TapCapQueryResponse> TapCapStatusAsync (SignedMessage signedMessage);

        /// <summary>
        /// TapCap current status
        /// </summary>
        /// <remarks>
        /// User TapCap status
        /// </remarks>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>Task of ApiResponse (TapCapQueryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TapCapQueryResponse>> TapCapStatusAsyncWithHttpInfo (SignedMessage signedMessage);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StatusApi : IStatusApi
    {
        private TapCapManager.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatusApi(String basePath)
        {
            this.Configuration = new TapCapManager.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = TapCapManager.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatusApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StatusApi(TapCapManager.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = TapCapManager.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = TapCapManager.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TapCapManager.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TapCapManager.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// TapCap history User TapCap history in the ranges provided
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>TapCapHistoryResponse</returns>
        public TapCapHistoryResponse TapCapHistory (SignedMessage signedMessage)
        {
             ApiResponse<TapCapHistoryResponse> localVarResponse = TapCapHistoryWithHttpInfo(signedMessage);
             return localVarResponse.Data;
        }

        /// <summary>
        /// TapCap history User TapCap history in the ranges provided
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>ApiResponse of TapCapHistoryResponse</returns>
        public ApiResponse< TapCapHistoryResponse > TapCapHistoryWithHttpInfo (SignedMessage signedMessage)
        {
            // verify the required parameter 'signedMessage' is set
            if (signedMessage == null)
                throw new ApiException(400, "Missing required parameter 'signedMessage' when calling StatusApi->TapCapHistory");

            var localVarPath = "./status/history";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signedMessage != null && signedMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signedMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signedMessage; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TapCapHistory", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TapCapHistoryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (TapCapHistoryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TapCapHistoryResponse)));
        }

        /// <summary>
        /// TapCap history User TapCap history in the ranges provided
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>Task of TapCapHistoryResponse</returns>
        public async System.Threading.Tasks.Task<TapCapHistoryResponse> TapCapHistoryAsync (SignedMessage signedMessage)
        {
             ApiResponse<TapCapHistoryResponse> localVarResponse = await TapCapHistoryAsyncWithHttpInfo(signedMessage);
             return localVarResponse.Data;

        }

        /// <summary>
        /// TapCap history User TapCap history in the ranges provided
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">Purchase Request info</param>
        /// <returns>Task of ApiResponse (TapCapHistoryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TapCapHistoryResponse>> TapCapHistoryAsyncWithHttpInfo (SignedMessage signedMessage)
        {
            // verify the required parameter 'signedMessage' is set
            if (signedMessage == null)
                throw new ApiException(400, "Missing required parameter 'signedMessage' when calling StatusApi->TapCapHistory");

            var localVarPath = "./status/history";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signedMessage != null && signedMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signedMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signedMessage; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TapCapHistory", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TapCapHistoryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (TapCapHistoryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TapCapHistoryResponse)));
        }

        /// <summary>
        /// TapCap current status User TapCap status
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>TapCapQueryResponse</returns>
        public TapCapQueryResponse TapCapStatus (SignedMessage signedMessage)
        {
             ApiResponse<TapCapQueryResponse> localVarResponse = TapCapStatusWithHttpInfo(signedMessage);
             return localVarResponse.Data;
        }

        /// <summary>
        /// TapCap current status User TapCap status
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>ApiResponse of TapCapQueryResponse</returns>
        public ApiResponse< TapCapQueryResponse > TapCapStatusWithHttpInfo (SignedMessage signedMessage)
        {
            // verify the required parameter 'signedMessage' is set
            if (signedMessage == null)
                throw new ApiException(400, "Missing required parameter 'signedMessage' when calling StatusApi->TapCapStatus");

            var localVarPath = "./status/summary";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signedMessage != null && signedMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signedMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signedMessage; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TapCapStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TapCapQueryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (TapCapQueryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TapCapQueryResponse)));
        }

        /// <summary>
        /// TapCap current status User TapCap status
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>Task of TapCapQueryResponse</returns>
        public async System.Threading.Tasks.Task<TapCapQueryResponse> TapCapStatusAsync (SignedMessage signedMessage)
        {
             ApiResponse<TapCapQueryResponse> localVarResponse = await TapCapStatusAsyncWithHttpInfo(signedMessage);
             return localVarResponse.Data;

        }

        /// <summary>
        /// TapCap current status User TapCap status
        /// </summary>
        /// <exception cref="TapCapManager.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signedMessage">TapCap status request</param>
        /// <returns>Task of ApiResponse (TapCapQueryResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TapCapQueryResponse>> TapCapStatusAsyncWithHttpInfo (SignedMessage signedMessage)
        {
            // verify the required parameter 'signedMessage' is set
            if (signedMessage == null)
                throw new ApiException(400, "Missing required parameter 'signedMessage' when calling StatusApi->TapCapStatus");

            var localVarPath = "./status/summary";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signedMessage != null && signedMessage.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signedMessage); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signedMessage; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TapCapStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TapCapQueryResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (TapCapQueryResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TapCapQueryResponse)));
        }

    }
}
