/* tslint:disable */
/* eslint-disable */
/**
 * @the-coin/rates-service
 * TheCoin rates service.  Publishes the official exchange rate for TheCore cryptocurrency into fiat currencies
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: stephen@thecoin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

