/**
 * THE Coin Broker Sample
 * TheCoin simple broker services.  This sample API is an example of how to setup the simplest low-volume exchange, when combined with the included server code, without external dependencies
 *
 * OpenAPI spec version: 0.1.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheBrokerCad);
  }
}(this, function(expect, TheBrokerCad) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheBrokerCad.PurchaseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PurchaseApi', function() {
    describe('completeCoinPurchase', function() {
      it('should call completeCoinPurchase successfully', function(done) {
        //uncomment below and update the code to test completeCoinPurchase
        //instance.completeCoinPurchase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmCoinPurchase', function() {
      it('should call confirmCoinPurchase successfully', function(done) {
        //uncomment below and update the code to test confirmCoinPurchase
        //instance.confirmCoinPurchase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('queryCoinPurchase', function() {
      it('should call queryCoinPurchase successfully', function(done) {
        //uncomment below and update the code to test queryCoinPurchase
        //instance.queryCoinPurchase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('queryCoinPurchasesIds', function() {
      it('should call queryCoinPurchasesIds successfully', function(done) {
        //uncomment below and update the code to test queryCoinPurchasesIds
        //instance.queryCoinPurchasesIds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestCoinPurchase', function() {
      it('should call requestCoinPurchase successfully', function(done) {
        //uncomment below and update the code to test requestCoinPurchase
        //instance.requestCoinPurchase(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
