// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'mainButton': string;
  'ui': string;
}
declare var cssExports: CssExports;
export = cssExports;
