// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerh3': string;
  'dollar': string;
  'gridWrapper': string;
  'h1': string;
  'h3': string;
  'h3left': string;
  'h3right': string;
  'headingWrapper': string;
  'inflation': string;
  'laptop': string;
  'links': string;
  'logoIcon': string;
  'mainWrapper': string;
  'sprout': string;
  'sproutWrapper': string;
  'subContainer': string;
  'subscribeText': string;
  'topMargin': string;
  'tree': string;
  'wallStreet': string;
  'yearStart': string;
}
declare var cssExports: CssExports;
export = cssExports;
