/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

import { resolve } from 'path';
import webpack from 'webpack';
import { merge } from "webpack-merge";
import HtmlWebpackPlugin from 'html-webpack-plugin';
import CircularDependencyPlugin from 'circular-dependency-plugin';
// import ErrorOverlayPlugin from './error-overlay-shim.cjs';

import { getBaseConfig } from './webpack.base';
import { signerConfig } from './webpack.signers';
import { getMocks } from "@thecointech/setenv/webpack";
import type { SecretKeyType } from '@thecointech/secrets';

import ReactRefreshWebpackPlugin from '@pmmmwh/react-refresh-webpack-plugin';
import ReactRefreshTypeScript from 'react-refresh-typescript';

const devOptions: webpack.Configuration = {
  mode: 'development',

  // Add hot reloading in development
  entry: [
    resolve('src', 'app.tsx'), // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        enforce: 'pre',
        use: [{
          loader: 'source-map-loader',
          options: {
            // Suppress:
            // Failed to parse source map from '/home/staylor/src/thecoin/node_modules/src/immer-reducer.ts'
            filterSourceMappingUrl: (url, resourcePath) => {
              if (
                /immer-reducer/.test(resourcePath) ||
                /IDX\/node_modules/.test(resourcePath)
              ) {
                return false;
              }
              return true;
            },
          },
        }],
      },
    ],
  },
  // Add development plugins
  plugins: [
    new ReactRefreshWebpackPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'src/index.html',
      favicon: 'src/images/favicon.png',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'cheap-module-source-map',
  performance: {
    hints: false,
  },

  devServer: {
    hot: true,
    historyApiFallback: true,
    // Port & other options should be supplied by the caller
  },
};

// We only post progress in dev mode, not dev:live
// This is because dev:live is streaming all packages
// at once, and the progress updates confuse the terminal
if (process.env.SETTINGS !== 'live') {
  devOptions.plugins.push(
    new webpack.ProgressPlugin(),
  )
}

export async function getDevConfig(secrets: SecretKeyType[] = [], overrides: Partial<webpack.Configuration> = {}): Promise<webpack.Configuration> {

  const baseConfig = await getBaseConfig(secrets);

  // Add in HMR to ts-loader plugin
  const tsLoader: any = baseConfig.module.rules.find((r: any) => r.use?.loader === 'ts-loader');
  if (!tsLoader) {
    throw new Error('ts-loader not found');
  }
  tsLoader.use.options.getCustomTransformers = () => ({
    before: [ReactRefreshTypeScript()].filter(Boolean),
  });
  return merge(
    overrides,
    getMocks(process.env),
    devOptions,
    signerConfig,
    baseConfig,
  )
}
